export const COUNTRIES = [
  // Core market
  { name: 'Egypt', code: 'EG' },
  { name: 'United Arab Emirates', code: 'AE' },
  { name: 'Saudi Arabia', code: 'SA' },
  { name: 'Kuwait', code: 'KW' },
  { name: 'Qatar', code: 'QA' },
  { name: 'Bahrain', code: 'BH' },
  { name: 'Oman', code: 'OM' },
  { name: 'Jordan', code: 'JO' },
  { name: 'Yemen', code: 'YE' },
  { name: 'Iraq', code: 'IQ' },
  { name: 'Libya', code: 'LY' },
  { name: 'Tunisia', code: 'TN' },
  { name: 'Algeria', code: 'DZ' },
  { name: 'Morocco', code: 'MA' },
  { name: 'Djibouti', code: 'DJ' },
  { name: 'Somalia', code: 'SO' },
  { name: 'Kenya', code: 'KE' },
  { name: 'Tanzania', code: 'TZ' },

  // Mediterranean
  { name: 'Greece', code: 'GR' },
  { name: 'Turkey', code: 'TR' },
  { name: 'Cyprus', code: 'CY' },
  { name: 'Lebanon', code: 'LB' },
  { name: 'Israel', code: 'IL' },
  { name: 'Malta', code: 'MT' },
  { name: 'Italy', code: 'IT' },
  { name: 'Spain', code: 'ES' },
  { name: 'France', code: 'FR' },
  { name: 'Gibraltar', code: 'GI' },

  // Major shipping nations
  { name: 'United Kingdom', code: 'GB' },
  { name: 'Germany', code: 'DE' },
  { name: 'Netherlands', code: 'NL' },
  { name: 'Norway', code: 'NO' },
  { name: 'Denmark', code: 'DK' },
  { name: 'Sweden', code: 'SE' },
  { name: 'Switzerland', code: 'CH' },
  { name: 'Belgium', code: 'BE' },
  { name: 'Portugal', code: 'PT' },
  { name: 'Panama', code: 'PA' },
  { name: 'Liberia', code: 'LR' },
  { name: 'Marshall Islands', code: 'MH' },
  { name: 'Bahamas', code: 'BS' },
  { name: 'Malta', code: 'MT' },
  { name: 'Singapore', code: 'SG' },
  { name: 'Hong Kong', code: 'HK' },
  { name: 'China', code: 'CN' },
  { name: 'Japan', code: 'JP' },
  { name: 'South Korea', code: 'KR' },
  { name: 'India', code: 'IN' },
  { name: 'Pakistan', code: 'PK' },
  { name: 'Bangladesh', code: 'BD' },
  { name: 'United States', code: 'US' },
  { name: 'Canada', code: 'CA' },
  { name: 'Australia', code: 'AU' },
  { name: 'New Zealand', code: 'NZ' },
  { name: 'Brazil', code: 'BR' },
  { name: 'South Africa', code: 'ZA' },
  { name: 'Nigeria', code: 'NG' },
  { name: 'Ghana', code: 'GH' },
  { name: 'Ethiopia', code: 'ET' },
  { name: 'Sudan', code: 'SD' },
  { name: 'Eritrea', code: 'ER' },
];

export const PORTS = [
  // Egypt & Red Sea
  { name: 'Port Said', code: 'EGPSD', region: 'Egypt & Red Sea' },
  { name: 'Alexandria', code: 'EGALY', region: 'Egypt & Red Sea' },
  { name: 'Suez', code: 'EGSUZ', region: 'Egypt & Red Sea' },
  { name: 'Ain Sokhna', code: 'EGASK', region: 'Egypt & Red Sea' },
  { name: 'Damietta', code: 'EGDAM', region: 'Egypt & Red Sea' },
  { name: 'Safaga', code: 'EGSFA', region: 'Egypt & Red Sea' },
  { name: 'Hurghada', code: 'EGUVA', region: 'Egypt & Red Sea' },
  { name: 'Nuweiba', code: 'EGNWB', region: 'Egypt & Red Sea' },
  { name: 'Sharm El-Sheikh', code: 'EGSSH', region: 'Egypt & Red Sea' },
  { name: 'Aqaba', code: 'JOAQJ', region: 'Egypt & Red Sea' },
  { name: 'Jeddah', code: 'SAJED', region: 'Egypt & Red Sea' },
  { name: 'Yanbu', code: 'SAYNB', region: 'Egypt & Red Sea' },
  { name: 'Duba', code: 'SADUB', region: 'Egypt & Red Sea' },

  // Gulf
  { name: 'Jebel Ali', code: 'AEJEA', region: 'Gulf' },
  { name: 'Dubai - Port Rashid', code: 'AEDXB', region: 'Gulf' },
  { name: 'Abu Dhabi - Zayed Port', code: 'AEAUH', region: 'Gulf' },
  { name: 'Abu Dhabi - Khalifa Port', code: 'AEKHP', region: 'Gulf' },
  { name: 'Sharjah', code: 'AESHJ', region: 'Gulf' },
  { name: 'Fujairah', code: 'AEFJR', region: 'Gulf' },
  { name: 'Ras Al Khaimah', code: 'AERKТ', region: 'Gulf' },
  { name: 'Muscat', code: 'OMMCT', region: 'Gulf' },
  { name: 'Salalah', code: 'OMSLL', region: 'Gulf' },
  { name: 'Kuwait City', code: 'KWKWI', region: 'Gulf' },
  { name: 'Dammam', code: 'SADMM', region: 'Gulf' },
  { name: 'Jubail', code: 'SAJUB', region: 'Gulf' },
  { name: 'Bahrain - Khalifa Bin Salman', code: 'BHKBS', region: 'Gulf' },
  { name: 'Doha', code: 'QADOH', region: 'Gulf' },

  // Mediterranean
  { name: 'Malta - Valletta', code: 'MTMLA', region: 'Mediterranean' },
  { name: 'Gibraltar', code: 'GIGIB', region: 'Mediterranean' },
  { name: 'Piraeus', code: 'GRPIR', region: 'Mediterranean' },
  { name: 'Thessaloniki', code: 'GRSKG', region: 'Mediterranean' },
  { name: 'Istanbul', code: 'TRIST', region: 'Mediterranean' },
  { name: 'Izmir', code: 'TRIZM', region: 'Mediterranean' },
  { name: 'Mersin', code: 'TRMER', region: 'Mediterranean' },
  { name: 'Limassol', code: 'CYLCA', region: 'Mediterranean' },
  { name: 'Beirut', code: 'LBBEY', region: 'Mediterranean' },
  { name: 'Haifa', code: 'ILHFA', region: 'Mediterranean' },
  { name: 'Tripoli (Libya)', code: 'LYTIP', region: 'Mediterranean' },
  { name: 'Tunis', code: 'TNTUN', region: 'Mediterranean' },
  { name: 'Algiers', code: 'DZALG', region: 'Mediterranean' },
  { name: 'Casablanca', code: 'MACAS', region: 'Mediterranean' },
  { name: 'Marseille', code: 'FRMRS', region: 'Mediterranean' },
  { name: 'Genoa', code: 'ITGOA', region: 'Mediterranean' },
  { name: 'Barcelona', code: 'ESBCN', region: 'Mediterranean' },

  // East Africa & Horn
  { name: 'Aden', code: 'YEADE', region: 'East Africa & Horn' },
  { name: 'Djibouti', code: 'DJJIB', region: 'East Africa & Horn' },
  { name: 'Berbera', code: 'SOBER', region: 'East Africa & Horn' },
  { name: 'Mombasa', code: 'KEMBA', region: 'East Africa & Horn' },
  { name: 'Dar es Salaam', code: 'TZDAR', region: 'East Africa & Horn' },
];

export const EGYPTPORTS = [
  { name: 'Port Said (EGPSD)', code: 'EGPSD' },
  { name: 'Alexandria (EGALY)', code: 'EGALY' },
  { name: 'Suez (EGSUZ)', code: 'EGSUZ' },
  { name: 'Ain Sokhna (EGASK)', code: 'EGASK' },
  { name: 'Safaga (EGSFA)', code: 'EGSFA' },
  { name: 'Hurghada (EGUVA)', code: 'EGUVA' },
  { name: 'Nuweiba (EGNWB)', code: 'EGNWB' },
  { name: 'Sharm El-Sheikh (EGSSH)', code: 'EGSSH' },
  { name: 'Damietta (EGDAM)', code: 'EGDAM' },
];

export const CURRENCIES = [
  // Major global
  { name: 'USD - US Dollar', code: 'USD', symbol: '$' },
  { name: 'EUR - Euro', code: 'EUR', symbol: '€' },
  { name: 'GBP - British Pound', code: 'GBP', symbol: '£' },
  { name: 'CHF - Swiss Franc', code: 'CHF', symbol: 'Fr' },
  { name: 'JPY - Japanese Yen', code: 'JPY', symbol: '¥' },
  { name: 'CNY - Chinese Yuan', code: 'CNY', symbol: '¥' },

  // Middle East
  { name: 'AED - UAE Dirham', code: 'AED', symbol: 'د.إ' },
  { name: 'SAR - Saudi Riyal', code: 'SAR', symbol: 'ر.س' },
  { name: 'QAR - Qatari Riyal', code: 'QAR', symbol: 'ر.ق' },
  { name: 'KWD - Kuwaiti Dinar', code: 'KWD', symbol: 'د.ك' },
  { name: 'BHD - Bahraini Dinar', code: 'BHD', symbol: 'د.ب' },
  { name: 'OMR - Omani Rial', code: 'OMR', symbol: 'ر.ع' },
  { name: 'JOD - Jordanian Dinar', code: 'JOD', symbol: 'د.ا' },
  { name: 'IQD - Iraqi Dinar', code: 'IQD', symbol: 'ع.د' },
  { name: 'YER - Yemeni Rial', code: 'YER', symbol: '﷼' },

  // North Africa
  { name: 'EGP - Egyptian Pound', code: 'EGP', symbol: 'ج.م' },
  { name: 'LYD - Libyan Dinar', code: 'LYD', symbol: 'ل.د' },
  { name: 'TND - Tunisian Dinar', code: 'TND', symbol: 'د.ت' },
  { name: 'DZD - Algerian Dinar', code: 'DZD', symbol: 'د.ج' },
  { name: 'MAD - Moroccan Dirham', code: 'MAD', symbol: 'د.م' },

  // Mediterranean & Europe
  { name: 'TRY - Turkish Lira', code: 'TRY', symbol: '₺' },
  { name: 'NOK - Norwegian Krone', code: 'NOK', symbol: 'kr' },
  { name: 'DKK - Danish Krone', code: 'DKK', symbol: 'kr' },
  { name: 'SEK - Swedish Krona', code: 'SEK', symbol: 'kr' },

  // Asia & other shipping nations
  { name: 'SGD - Singapore Dollar', code: 'SGD', symbol: 'S$' },
  { name: 'HKD - Hong Kong Dollar', code: 'HKD', symbol: 'HK$' },
  { name: 'INR - Indian Rupee', code: 'INR', symbol: '₹' },
  { name: 'PKR - Pakistani Rupee', code: 'PKR', symbol: '₨' },
  { name: 'BDT - Bangladeshi Taka', code: 'BDT', symbol: '৳' },
  { name: 'KES - Kenyan Shilling', code: 'KES', symbol: 'KSh' },
  { name: 'TZS - Tanzanian Shilling', code: 'TZS', symbol: 'TSh' },
];

export const VESSELTYPE = [
  { name: 'General Cargo', code: 'GENERAL_CARGO' },
  { name: 'Bulk Carrier', code: 'BULK_CARRIER' },
  { name: 'Tanker', code: 'TANKER' },
  { name: 'Container', code: 'CONTAINER' },
  { name: 'Ro-Ro', code: 'RORO' },
  { name: 'Passenger', code: 'PASSENGER' },
  { name: 'Offshore Supply', code: 'OFFSHORE' },
  { name: 'Tug', code: 'TUG' },
  { name: 'Dredger', code: 'DREDGER' },
  { name: 'Fishing', code: 'FISHING' },
  { name: 'Research', code: 'RESEARCH' },
  { name: 'Other', code: 'OTHER' },
];

export const VESSELSTATUS = [
  { name: 'Active', code: 'ACTIVE' },
  { name: 'Laid Up', code: 'LAID_UP' },
  { name: 'Dry Dock', code: 'DRY_DOCK' },
  { name: 'Scrapped', code: 'SCRAPPED' },
];

export const TRADEROUTES = [
  { name: 'Mediterranean', code: 'MED' },
  { name: 'Red Sea', code: 'RED_SEA' },
  { name: 'Arabian Gulf', code: 'GULF' },
  { name: 'Mediterranean & Red Sea', code: 'MED_RED' },
  { name: 'Indian Ocean', code: 'INDIAN' },
  { name: 'West Africa', code: 'WEST_AFRICA' },
  { name: 'East Africa', code: 'EAST_AFRICA' },
  { name: 'North Europe', code: 'NORTH_EU' },
  { name: 'Worldwide', code: 'WORLDWIDE' },
];
