import { Injectable } from '@angular/core';
import { of } from 'rxjs';

export interface Payment {
  id: string;
  type: string;
  date: string;
  customer: string;
  invoiceNumber: number;
  customerInvoice: number;
  amountPaid: number;
  method: string;
}

@Injectable({
  providedIn: 'root',
})
export class PaymentsService {
  getProducts() {
    return of([
      {
        id: 'PY-109-221',
        type: 'Customer',
        customer: 'Trade Lion/Wonderville',
        date: '12/09/2025',
        invoiceNumber: 12,
        customerInvoice: 922001,
        method: 'Bank Transfer',
        amountPaid: 12010,
      },
      {
        id: 'PY-209-221',
        type: 'Supplier',
        customer: 'Trade Lion/Wonderville',
        date: '12/09/2025',
        invoiceNumber: 12,
        customerInvoice: 922001,
        method: 'Bank Transfer',
        amountPaid: 12010,
      },
      {
        id: 'PY-109-321',
        type: 'Customer',
        customer: 'Trade Lion/Wonderville',
        date: '12/09/2025',
        invoiceNumber: 12,
        customerInvoice: 922001,
        method: 'Bank Transfer',
        amountPaid: 12010,
      },
      {
        id: 'PY-109-421',
        type: 'Supplier',
        customer: 'Trade Lion/Wonderville',
        date: '12/09/2025',
        invoiceNumber: 12,
        customerInvoice: 922001,
        method: 'Bank Transfer',
        amountPaid: 12010,
      },
      {
        id: 'PY-109-521',
        type: 'Customer',
        customer: 'Trade Lion/Wonderville',
        date: '12/09/2025',
        invoiceNumber: 12,
        customerInvoice: 922001,
        method: 'Bank Transfer',
        amountPaid: 12010,
      },
      {
        id: 'PY-109-521',
        type: 'Supplier',
        customer: 'Trade Lion/Wonderville',
        date: '12/09/2025',
        invoiceNumber: 12,
        customerInvoice: 922001,
        method: 'Bank Transfer',
        amountPaid: 12010,
      },
      {
        id: 'PY-109-521',
        type: 'Customer',
        customer: 'Trade Lion/Wonderville',
        date: '12/09/2025',
        invoiceNumber: 12,
        customerInvoice: 922001,
        method: 'Bank Transfer',
        amountPaid: 12010,
      },
      {
        id: 'PY-109-621',
        type: 'Supplier',
        customer: 'Trade Lion/Wonderville',
        date: '12/09/2025',
        invoiceNumber: 12,
        customerInvoice: 922001,
        method: 'Bank Transfer',
        amountPaid: 12010,
      },
      {
        id: 'PY-109-721',
        type: 'Customer',
        customer: 'Trade Lion/Wonderville',
        date: '12/09/2025',
        invoiceNumber: 12,
        customerInvoice: 922001,
        method: 'Bank Transfer',
        amountPaid: 12010,
      },
      {
        id: 'PY-109-821',
        type: 'Customer',
        customer: 'Trade Lion/Wonderville',
        date: '12/09/2025',
        invoiceNumber: 12,
        customerInvoice: 922001,
        method: 'Bank Transfer',
        amountPaid: 12010,
      },
      {
        id: 'PY-104-821',
        type: 'Customer',
        customer: 'Trade Lion/Wonderville',
        date: '12/09/2025',
        invoiceNumber: 12,
        customerInvoice: 922001,
        method: 'Bank Transfer',
        amountPaid: 12010,
      },
      {
        id: 'PY-109-221',
        type: 'Supplier',
        customer: 'Trade Lion/Wonderville',
        date: '12/09/2025',
        invoiceNumber: 12,
        customerInvoice: 922001,
        method: 'Bank Transfer',
        amountPaid: 12010,
      },
      {
        id: 'PY-109-221',
        type: 'Customer',
        customer: 'Trade Lion/Wonderville',
        date: '12/09/2025',
        invoiceNumber: 12,
        customerInvoice: 922001,
        method: 'Bank Transfer',
        amountPaid: 12010,
      },
      {
        id: 'PY-109-221',
        type: 'Supplier',
        customer: 'Trade Lion/Wonderville',
        date: '12/09/2025',
        invoiceNumber: 12,
        customerInvoice: 922001,
        method: 'Bank Transfer',
        amountPaid: 12010,
      },
      {
        id: 'PY-109-221',
        type: 'Customer',
        customer: 'Trade Lion/Wonderville',
        date: '12/09/2025',
        invoiceNumber: 12,
        customerInvoice: 922001,
        method: 'Bank Transfer',
        amountPaid: 12010,
      },
      {
        id: 'PY-109-221',
        type: 'Supplier',
        customer: 'Trade Lion/Wonderville',
        date: '12/09/2025',
        invoiceNumber: 12,
        customerInvoice: 922001,
        method: 'Bank Transfer',
        amountPaid: 12010,
      },
      {
        id: 'PY-109-221',
        type: 'Customer',
        customer: 'Trade Lion/Wonderville',
        date: '12/09/2025',
        invoiceNumber: 12,
        customerInvoice: 922001,
        method: 'Bank Transfer',
        amountPaid: 12010,
      },
      {
        id: 'PY-109-221',
        type: 'Customer',
        customer: 'Trade Lion/Wonderville',
        date: '12/09/2025',
        invoiceNumber: 12,
        customerInvoice: 922001,
        method: 'Bank Transfer',
        amountPaid: 12010,
      },
      {
        id: 'PY-109-221',
        type: 'Customer',
        customer: 'Trade Lion/Wonderville',
        date: '12/09/2025',
        invoiceNumber: 12,
        customerInvoice: 922001,
        method: 'Bank Transfer',
        amountPaid: 12010,
      },
      {
        id: 'PY-109-221',
        type: 'Customer',
        customer: 'Trade Lion/Wonderville',
        date: '12/09/2025',
        invoiceNumber: 12,
        customerInvoice: 922001,
        method: 'Bank Transfer',
        amountPaid: 12010,
      },
      {
        id: 'PY-109-221',
        type: 'Customer',
        customer: 'Trade Lion/Wonderville',
        date: '12/09/2025',
        invoiceNumber: 12,
        customerInvoice: 922001,
        method: 'Bank Transfer',
        amountPaid: 12010,
      },
      {
        id: 'PY-109-221',
        type: 'Customer',
        customer: 'Trade Lion/Wonderville',
        date: '12/09/2025',
        invoiceNumber: 12,
        customerInvoice: 922001,
        method: 'Bank Transfer',
        amountPaid: 12010,
      },
      {
        id: 'PY-109-221',
        type: 'Customer',
        customer: 'Trade Lion/Wonderville',
        date: '12/09/2025',
        invoiceNumber: 12,
        customerInvoice: 922001,
        method: 'Bank Transfer',
        amountPaid: 12010,
      },
      {
        id: 'PY-109-221',
        type: 'Customer',
        customer: 'Trade Lion/Wonderville',
        date: '12/09/2025',
        invoiceNumber: 12,
        customerInvoice: 922001,
        method: 'Bank Transfer',
        amountPaid: 12010,
      },
    ]);
  }
}
